# Generated by Django 3.2.9 on 2021-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.CharField(max_length=500)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('custom_title', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.CharField(max_length=500)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='planets',
            name='custom_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planets',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
