# Generated by Django 3.2.9 on 2021-11-05 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_movies_custom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
