# Generated by Django 3.2.9 on 2021-11-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_movies_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
    ]
