# Generated by Django 3.2.9 on 2021-11-06 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
